export const THANKS = [
  "Thanks!",
  "Took you long enough...",
  "Thank you!",
  "Peace",
  "See ya",
  "Next time could you go faster? Thanks.",
  "Wow you're really good at pushing that button",
  "Thx <3",
  "Wow, finally...",
];

export const GREETINGS = {
  all: [
    "Yo",
    "Sup",
    "Hey!",
    "What's up",
    "Welcome",
    "Welcome to my floor",
    "Get out of my room!",
    "Hi",
  ],
  wud: ["￼"],
  "plague-blvd": [],
  wendigo: [],
  biv: [],
  blckk: [],
  bruhmanegod: [],
  changeline: [],
  cherry: [],
  cubensis: [],
  cxrpse: [],
  deerdeath: [],
  dirtybutt: [],
  kamaara: [],
  bvdlvd: ["HEY SKOTSKR! COULD YOU TURN IT DOWN?", "ITS BAD-LAD"],
  skotskr: [],
  mkultra: [],
  greg: [],
  jake: [],
  sorbet: ["Good morning!", "One more thing...", "I love strawberries"],
  steel: [],
  wes: ["Hello world"],
  darkie: ["What?", "Yuh", "Let's write a haiku"],
  hxstage: [],
};
